### ISSUE TITLE
Build Error: hardware_qcom-caf_wlan

### ISSUE THREAD

**Issue by shoya0x00** [halcyonproject/issue_tracker#5]
# Halcyon Issue Tracker

## Describe the issue you faced with Halcyon
```
while building from latest source. got issue related to hardware/qcom-caf/wlan
```

## Where do you faced this issue?
```
Source side:
hardware/qcom-caf/wlan/qcwcn/wifi_hal/wificonfig.cpp:1723:16: error: use of undeclared identifier 'WIFI_VOIP_MODE_VOICE'
        (mode==WIFI_VOIP_MODE_VOICE) ? 1 : 0)) {
               ^
1 error generated.
```

## On which device does this issue occur?
```
POCO X3 (surya)
```

## Your device source codes
```
https://github.com/surya-aosp/device_xiaomi_surya
```

## Attachment
```
https://paste.mozilla.org/C3676Tqb/raw
```

**Comment by neroices** [comment]
Try revert this commit
https://github.com/LineageOS/android_hardware_qcom_wlan/commit/639d890293ce85b821bfe668e2fcc8e862e1a051

**Comment by shoya0x00** [comment]
hardware/qcom-caf/wlan/qcwcn/wifi_hal/wificonfig.cpp:1723:44: error: expected ')'
        (mode==WIFI_VOIP_MODE_ON ? 1 : 0)) {
                                           ^
hardware/qcom-caf/wlan/qcwcn/wifi_hal/wificonfig.cpp:1722:8: note: to match this '('
    if (wifiConfigCommand->put_u8(QCA_WLAN_VENDOR_ATTR_CONFIG_WFC_STATE,
       ^
1 error generated.
19:09:33 ninja failed with: exit status 1

#### failed to build some targets (07:27 (mm:ss)) ####

new error emarges. https://github.com/PixelExperience/hardware_qcom-caf_wlan don't give this error
also tried the https://github.com/halcyonproject/hardware_qcom-caf_wlan Ursinia branch no error there

**Comment by shoya0x00** [comment]
build was success thanks
